### ISSUE TITLE
I can't figure this out...env string not read.

### ISSUE THREAD

**Issue by SpiralBlu** [alchemyplatform/hello-world-tutorial#2]
I have written out the code, copied the code.  I have the .env file created with my API_URL and PRIVATE_KEY in it, but VSCode keeps saying that PRIVATE_KEY is declared but it's value is never read.  (ts6133).  I have puzzled over this for about 3 hours hoping to figure it out.

Really appreciate the class on creating smart contracts.  I'm just stuck and really want to learn.

When I try to compile it gives an error: "* Invalid account: #0 for network: ropsten - private key too short, expected 32 bytes"

VSCode never highlights the accounts PRIVATE_KEY string either.

Any thoughts would be helpful.  I'm sure it's something simple stupid.

![hello-world-hardhat-config-js](https://user-images.githubusercontent.com/104639899/169719229-9e7d1083-d4ca-4829-a55c-9de8327c3782.png)

**Comment by jaypaik** [comment]
Looks like you want backticks here instead of a single quote:
```diff
-        accounts: ['0x${PRIVATE_KEY}']
+        accounts: [`0x${PRIVATE_KEY}`]
```

See: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

Hope that helps!

**Comment by SpiralBlu** [comment]
> Looks like you want backticks here instead of a single quote:
> 
> ```diff
> -        accounts: ['0x${PRIVATE_KEY}']
> +        accounts: [`0x${PRIVATE_KEY}`]
> ```
> 
> See: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals
> 
> Hope that helps!

Doh...I bet you're right.  I knew it had to be something simple stupid.  Teaches me to swing from Python to Solidity.

The error had me thinking it wasn't picking the variable up out of .env.

**Comment by SpiralBlu** [comment]
That's what it was.  Thank you for a second set of eyes.  I was sure it was something stupid simple.
